apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: gugotik-auth-service
  name: gugotik-auth-service
  namespace: gugotik-service-bundle
spec:
  selector:
    matchLabels:
      name: gugotik-auth-service
  template:
    metadata:
      labels:
        app: gugotik-auth-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gugotik-auth-service
        dream-app: gugotik-auth-service
        dream-unit: gugotik-auth-service
    spec:
      imagePullSecrets:
        -   name: reg-cred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gugotik-auth-service
            command:
              - ./services/AuthService
            envFrom:
              -   configMapRef:
                    name: env-config
            ports:
              - name: grpc-37001
                containerPort: 37001
                protocol: TCP
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 8Mi
      terminationGracePeriodSeconds: 30