apiVersion: v1
kind: Service
metadata:
  labels:
    app: clash
  name: clash
  namespace: epicmo-clash
spec:
  ports:
    - name: http-proxy
      port: 7890
      protocol: TCP
      targetPort: 7890
    - name: socket-proxy
      port: 7891
      protocol: TCP
      targetPort: 7891
  selector:
    name: clash
  type: ClusterIP