apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gugotik-publish-service
  name: gugotik-publish-service
  namespace: gugotik-service-bundle
spec:
  selector:
    matchLabels:
      name: gugotik-publish-service
  template:
    metadata:
      labels:
        app: gugotik-publish-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gugotik-publish-service
        dream-app: gugotik-publish-service
        dream-unit: gugotik-publish-service
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: storage
      imagePullSecrets:
        -   name: regcred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gugotik-publish-service
            command:
              - ./services/publish/PublishService
            envFrom:
              -   configMapRef:
                    name: env-config
              - configMapRef:
                  name: gugotik-env
              - secretRef:
                  name: gugotik-secret
            ports:
              - name: grpc-37005
                containerPort: 37005
                protocol: TCP
              - name: metrics-37099
                containerPort: 37099
                protocol: TCP
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
              - mountPath: /data/apps/gugotik-service-bundle/data
                name: volume
      terminationGracePeriodSeconds: 30