apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gugotik-message-service
  name: gugotik-message-service
  namespace: gugotik-service-bundle
spec:
  selector:
    matchLabels:
      name: gugotik-message-service
  template:
    metadata:
      labels:
        app: gugotik-message-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gugotik-message-service
        dream-app: gugotik-message-service
        dream-unit: gugotik-message-service
    spec:
      imagePullSecrets:
        -   name: regcred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gugotik-message-service
            command:
              - ./services/message/MessageService
            envFrom:
              -   configMapRef:
                    name: env-config
              - configMapRef:
                  name: gugotik-env
              - secretRef:
                  name: gugotik-secret
            ports:
              - name: grpc-37007
                containerPort: 37007
                protocol: TCP
              - name: metrics-37099
                containerPort: 37099
                protocol: TCP
            resources:
              limits:
                cpu: 2000m
                memory: 2048Mi
              requests:
                cpu: 100m
                memory: 128Mi
      terminationGracePeriodSeconds: 30