apiVersion: v1
kind: Service
metadata:
  labels:
    app: gugotik-publish-service
  name: gugotik-publish-service
  namespace: gugotik-service-bundle
spec:
  ports:
    - name: grpc
      port: 37005
      protocol: TCP
      targetPort: 37005
  selector:
    name: gugotik-publish-service
    branch: dev
  type: ClusterIP