apiVersion: v1
kind: Service
metadata:
  labels:
    app: gugotik-auth-service
  name: gugotik-auth-service
  namespace: gugotik-service-bundle
spec:
  ports:
    - name: grpc
      port: 37001
      protocol: TCP
      targetPort: 37001
  selector:
    name: gugotik-auth-service
    branch: master
  type: ClusterIP