name: Code Scan
on:
  workflow_dispatch:
  pull_request:
    branches: [ "dev" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    environment: Analysis
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
